### PR TITLE
Feature/misc fixes

### LINKED ISSUE #61: There is no way to clear an input via keyboard.
Scenario:
I am navigating a form via Tab. I focus a cosmoz-autocomplete input with 1 chip already selected (1 chip limit). 

Expectation: 
I expect that when I hit Backspace or Delete, the chip is cleared and I can input a value.

Reality:
Nothing happens. The only way to clear the selection is via mouse.

### LINKED ISSUE #74: More control regarding container
Re https://neovici.slack.com/archives/C6LJQMJFM/p1604318318445000?thread_ts=1604317841.443000&cid=C6LJQMJFM

It would be great to be able to define the container element for which the position is calculated.

### LINKED ISSUE #75: Misc improvements
- [x] Add `part` attributes to style different parts of the ui: input, chip, chips 
- [x] Don't show clear icon when the autocomplete is disabled
- [x] Add title to chips to show when text is overflowing

### PR DESCRIPTION
**Pull request by megheaiulian**
fixes #75 
fixes #61 
fixes #74

### CODE REVIEW

File: lib/autocomplete.js [hunk 1]
```diff
@@ -9,18 +9,19 @@ import { useHost } from '@neovici/cosmoz-utils/lib/hooks/use-host';
...
+const chip = (text, onClear, disabled) => html`
+		<div class="chip" part="chip" title=${ text }>
+			<span class="chip-text" part="chip-text">${ text }</span>
+			${ !disabled && html`
+			<span class="chip-clear" part="chip-clear" @click=${ onClear }>
 				<svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" focusable="false">
 					<g><path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"></path></g>
 				</svg>
-			</span>
+			</span>` || '' }
```
Comment (cristinecula) [inline lib/autocomplete.js:20]: Doesn't `nothing` (from lit-html) make more sense instead of empty string?

**Review by cristinecula — APPROVED** [review]
Great!

**Review by cristinecula — APPROVED** [review]
