### PR TITLE
fix(autocomplete): better ui for single selection

### LINKED ISSUE #57: Clearer single-selection UI
Initial responses to the new component include confusion around the single-item-selectable selected state.

Currently, paper-autocomplete-chips displays it like this:
image

With cosmoz-autocomplete, it becomes:
image

For shorter values, it becomes even weirder:
image

The important thing is to convey to the user that an item is selected and no further selections are possible. I think it could even be beneficial to force the user to clear the selection before doing a new one.

A compromise might be to keep the chip layout but to expand it completely in the input (but with the smaller label float):
image

### PR DESCRIPTION
**Pull request by megheaiulian**
Fixes #57

### CODE REVIEW

File: lib/autocomplete.js [hunk 1]
```diff
@@ -39,59 +89,22 @@ const chip = (text, onClear) => html`
...
 
 			<paper-input
 				id="input"
 				.label=${ label }
 				.errorMessage=${ errorMessage }
 				.placeholder=${ placeholder }
+				?readonly=${ isSingle }
 				?no-label-float=${ noLabelFloat }
-				?always-float-label=${ alwaysFloatLabel }
+				?always-float-label=${ isSingle ? true : alwaysFloatLabel }
```
Comment (nomego) [inline lib/autocomplete.js:107]:
```suggestion
				?always-float-label=${ isSingle || alwaysFloatLabel }
```

File: lib/autocomplete.js [hunk 2]
```diff
@@ -101,10 +114,10 @@ const chip = (text, onClear) => html`
 			>
 				<slot name="prefix" slot="prefix"></slot>
 				<slot name="suffix" slot="suffix"></slot>
-				${ (limit === 1 || '') && $chips }
+				${ (limit === 1 || '') && html`<div class="chips" slot="prefix">${ $chips }</div>` }
 			</paper-input>
 
-			${ (items.length || '') &&
+			${ (!isSingle && items.length || '') &&
```
Comment (nomego) [inline lib/autocomplete.js:120]:
```suggestion
			${ !isSingle && items.length &&
```
?
